services:
  paladin:
    build: .
    container_name: paladin
    volumes:
      - ./config.toml:/app/config.toml
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    depends_on:
      - mongo
    environment:
      - WORKERS=${WORKERS}
      - PORT=${CONTAINER_PORT}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: paladin-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
